Connect udp
rcory/drake pull request #9
Opened 2020-03-05 18:51 UTC by hongkai-dai

Rotate the brick through UDP message.

To demo the PR, run the following two commands

1. In one terminal, do `run_planar_gripper_qp_udp_controller --publisher_remote_address=xxxxx`
2. In another terminal, do `run_planar_gripper_rotate_simulation --use_QP=UDP --publisher_remote_address=xxxxxxx`

where --publisher_remote_address should be equal to the unsigned long value of the machine IP address. I converted the IP address to unsigned long through https://www.smartconversion.com/unit_conversion/IP_Address_Converter.aspx

2020-03-06 02:01 UTC, hongkai-dai commented
This  PR is ready for review. I updated the code and now the brick is rotated to the desired pose

2020-03-06 19:00 UTC, rcory reviewed
+@rcory for review.

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/9#-:-M1l6KXI-bgNHrUhSL5R:brrmq6i)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @rcory)



<!-- Sent from Reviewable.io -->

2020-03-06 21:34 UTC, rcory requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/9)* status: all files reviewed, 25 unresolved discussions (waiting on @hongkai-dai)

___
*[examples/planar_gripper/BUILD.bazel, line 171 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lGmtd-VR25rkuL343:-M1lGmtd-VR25rkuL344:bt72kyp) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/BUILD.bazel#L171)):*
> ```Starlark
> 
> drake_cc_binary(
>     name = "run_planar_gripper_qp_udp_controller",
> ```

Now that we have a UDP version of this file, perhaps we should rename `run_planar_gripper_qp_controller.cc` to `run_planar_gripper_qp_lcm_controller`.
___
*[examples/planar_gripper/BUILD.bazel, line 182 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lNHKw3tuVfB69Pjba:-M1lNHKw3tuVfB69Pjbb:bktvnwo) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/BUILD.bazel#L182)):*
> ```Starlark
>         "//lcmtypes:planar_gripper_qp",
>         "//systems/analysis:simulator",
>         "//systems/lcm:lcm_pubsub_system",
> ```

I don't think you need any of the 3 LCM dependencies listed above, since this is the UDP version?
___
*[examples/planar_gripper/finger_brick_control.h, line 268 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1liTf5B91qY9hmNATC:-M1liTf5B91qY9hmNATD:buow2en) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/finger_brick_control.h#L268)):*
> ```objc
>     const std::optional<std::unordered_map<Finger, ForceController&>>&
>         finger_force_control_map,
>     const QPControlOptions& qpoptions, int publisher_local_port,
> ```

add the port/address vars to the documentation above?
___
*[examples/planar_gripper/finger_brick_control.cc, line 1135 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lj2C21HGr4yzHa5S1:-M1lj2C21HGr4yzHa5S2:b3iv9fn) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/finger_brick_control.cc#L1135)):*
> ```cpp
>       "plant_spatial_force", planar_gripper.GetInputPort("spatial_force")));
> 
>   // Adds the LCM QP Controller to the diagram.
> ```

says LCM
___
*[examples/planar_gripper/finger_brick_control.cc, line 1139 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljBka9NLG85U35Rv0:-M1ljBka9NLG85U35Rv1:b-70dlqz) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/finger_brick_control.cc#L1139)):*
> ```cpp
>   auto qp_controller = builder->AddSystem<PlanarGripperQPControllerUDP>(
>       planar_gripper.get_multibody_plant().num_multibody_states(),
>       GetBrickBodyIndex(planar_gripper.get_multibody_plant()),
> ```

brick body index isn't used? (tied to my other comment above)
___
*[examples/planar_gripper/finger_brick_control.cc, line 1169 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljN4w6C0FexxYbyg4:-M1ljN4x696fUqREet13:b3iv9fn) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/finger_brick_control.cc#L1169)):*
> ```cpp
>       qp_controller->GetInputPort("qp_desired_brick_state")));
> 
>   // Connects the LCM QP controller.
> ```

says LCM
___
*[examples/planar_gripper/planar_gripper_lcm.cc, line 433 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljdE214uIiagzQnlt:-M1ljdE214uIiagzQnlu:b-jmx1mo) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/planar_gripper_lcm.cc#L433)):*
> ```cpp
>               << qp_finger_control.second.F_Bq_W.translational().transpose()
>               << "\n";
>   }
> ```

This whole block is probably debugging code?
___
*[examples/planar_gripper/planar_gripper_lcm.cc, line 525 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljj33C4SnyG-sPUl5:-M1ljj33C4SnyG-sPUl6:b17emrk) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/planar_gripper_lcm.cc#L525)):*
> ```cpp
>               plant_state.data());
>   }
>   std::cout << "plant state: " << plant_state.transpose() << "\n";
> ```

debug code?
___
*[examples/planar_gripper/planar_gripper_lcm.cc, line 614 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljnpt2rmaFSegSXjj:-M1ljnpt2rmaFSegSXjk:bkjr9wu) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/planar_gripper_lcm.cc#L614)):*
> ```cpp
>                 << to_string(assignment.second.first) << " at "
>                 << assignment.second.second.transpose() << "\n";
>     }
> ```

this block is probably debug code?
___
*[examples/planar_gripper/planar_gripper_lcm.cc, line 737 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljqqyBIYGXkSFQp8c:-M1ljqqyBIYGXkSFQp8d:b-2tyyx0) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/planar_gripper_lcm.cc#L737)):*
> ```cpp
>   }
>   std::cout << "brick_desired_state " << brick_state.transpose() << "\n";
>   std::cout << "brick_desired_accel " << brick_accel.transpose() << "\n";
> ```

two lines above are debug code?
___
*[examples/planar_gripper/planar_gripper_udp.h, line 405 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lIw5o0U3dKvg4eVik:-M1lIw5o0U3dKvg4eVil:btb2n5n) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/planar_gripper_udp.h#L405)):*
> ```objc
> 
>   int file_descriptor_{};
>   int local_port_{};
> ```

Compiler says this is unused, and I get a build error.
___
*[examples/planar_gripper/run_planar_gripper_qp_controller.cc, line 11 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lNVM--deRlp63JOa1:-M1lNVM--deRlp63JOa2:bfw0maj) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/run_planar_gripper_qp_controller.cc#L11)):*
> ```cpp
> #include "drake/examples/planar_gripper/planar_gripper_lcm.h"
> #include "drake/examples/planar_gripper/planar_gripper.h"
> #include "drake/examples/planar_gripper/finger_brick.h"
> ```

Don't need this.
___
*[examples/planar_gripper/run_planar_gripper_qp_controller.cc, line 37 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lNWucDPC7E3tYethR:-M1lNWud7ITRQPOc55y0:b-k10qr6) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/run_planar_gripper_qp_controller.cc#L37)):*
> ```cpp
>     zc, 0,
>     "Value of z-coordinate offset for y-face contact (for brick-only sim.");
> ```

extra space?
___
*[examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc, line 3 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lOjqh2QpMTDd0oP0y:-M1lOjqi1UVuvfDF0HJ8:bjee2oh) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc#L3)):*
> ```cpp
> /// @file
> ///
> /// Implements an LCM based finger/brick QP controller.
> ```

LCM => UDP
___
*[examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc, line 4 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lOlvv47MecI3nFusu:-M1lOlvv47MecI3nFusv:b-kxu7v0) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc#L4)):*
> ```cpp
> ///
> /// Implements an LCM based finger/brick QP controller.
> // TODO(rcory) This file is still a WIP.
> ```

Remove this comment
___
*[examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc, line 8 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lN_Jd8D8oBB683iJa:-M1lN_Jd8D8oBB683iJb:bwokqqs) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc#L8)):*
> ```cpp
> #include <gflags/gfla [...]

2020-03-06 22:09 UTC, hongkai-dai reviewed
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/9)* status: all files reviewed, 25 unresolved discussions (waiting on @rcory)

___
*[examples/planar_gripper/BUILD.bazel, line 171 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lGmtd-VR25rkuL343:-M1lpk5X3pBV6eU0oUMe:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/BUILD.bazel#L171)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Now that we have a UDP version of this file, perhaps we should rename `run_planar_gripper_qp_controller.cc` to `run_planar_gripper_qp_lcm_controller`.
</blockquote></details>

Done.
___
*[examples/planar_gripper/BUILD.bazel, line 182 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lNHKw3tuVfB69Pjba:-M1lq-MbDUSOZ9HS34n8:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/BUILD.bazel#L182)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

I don't think you need any of the 3 LCM dependencies listed above, since this is the UDP version?
</blockquote></details>

Done.
___
*[examples/planar_gripper/finger_brick_control.h, line 268 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1liTf5B91qY9hmNATC:-M1lqlgj3U-M8TiovFkE:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/finger_brick_control.h#L268)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

add the port/address vars to the documentation above?
</blockquote></details>

Done.
___
*[examples/planar_gripper/finger_brick_control.cc, line 1135 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lj2C21HGr4yzHa5S1:-M1lqqqYEtcSp2e3JIKN:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/finger_brick_control.cc#L1135)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

says LCM
</blockquote></details>

Done.
___
*[examples/planar_gripper/finger_brick_control.cc, line 1139 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljBka9NLG85U35Rv0:-M1lr2wA8N8h8iWfvr_Y:bb4gnzy) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/finger_brick_control.cc#L1139)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

brick body index isn't used? (tied to my other comment above)
</blockquote></details>

It is used when I construct the UDP message.
___
*[examples/planar_gripper/finger_brick_control.cc, line 1169 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljN4w6C0FexxYbyg4:-M1lr9kACbV22qmUwWMp:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/finger_brick_control.cc#L1169)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

says LCM
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper_lcm.cc, line 433 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljdE214uIiagzQnlt:-M1lrC3VCkwRFhMyf0XZ:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/planar_gripper_lcm.cc#L433)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

This whole block is probably debugging code?
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper_lcm.cc, line 525 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljj33C4SnyG-sPUl5:-M1lrCeT-RUJh3bvKfbC:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/planar_gripper_lcm.cc#L525)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

debug code?
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper_lcm.cc, line 614 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljnpt2rmaFSegSXjj:-M1lrDV43d_7ygSgVOiP:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/planar_gripper_lcm.cc#L614)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

this block is probably debug code?
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper_lcm.cc, line 737 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljqqyBIYGXkSFQp8c:-M1lrEI94ooKkmpcg-k7:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/planar_gripper_lcm.cc#L737)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

two lines above are debug code?
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper_udp.h, line 405 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lIw5o0U3dKvg4eVik:-M1lrFLj1Fe-gVrVvORa:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/planar_gripper_udp.h#L405)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Compiler says this is unused, and I get a build error.
</blockquote></details>

Done.
___
*[examples/planar_gripper/run_planar_gripper_qp_controller.cc, line 11 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lNVM--deRlp63JOa1:-M1lrXrz8tkcUkpVBNgP:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/run_planar_gripper_qp_controller.cc#L11)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Don't need this.
</blockquote></details>

Done.
___
*[examples/planar_gripper/run_planar_gripper_qp_controller.cc, line 37 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lNWucDPC7E3tYethR:-M1lr_OA5bJDE53YJyk_:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/run_planar_gripper_qp_controller.cc#L37)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

extra space?
</blockquote></details>

Done.
___
*[examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc, line 3 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lOjqh2QpMTDd0oP0y:-M1lreAYABQf6xT1NkSB:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc#L3)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

LCM => UDP
</blockquote></details>

Done.
___
*[examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc, line 4 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lOlvv47MecI3nFusu:-M1lrfim8vrOompcuB6b:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc#L4)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Remove this comment
</blockquote></details>

Done.
___
*[examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc, line 8 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lN_Jd8D8oBB683iJa:-M1lriylCa8vSLirar9f:b-h72gia) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc#L8)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Since you don't need access to the brick's body index (see comment below), I don't need this header?
</blockquote></details>

I think I need the body index to construct the UDP receiver. I do not use it within the UDP message, but I kept it there because drake::math::ExternallyAppliedSpatialForce needs a b [...]

2020-03-06 22:45 UTC, rcory requested changes
Fyi, there's a merge conflict.

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/9#-:-M1lu7qdDmtvbJb9hdsv:bj6xdls)* status: all files reviewed, 3 unresolved discussions (waiting on @hongkai-dai)

___
*[examples/planar_gripper/finger_brick_control.cc, line 1139 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljBka9NLG85U35Rv0:-M1m0Iqz-8ZjVQ1RP7JM:b-i6cas8) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/finger_brick_control.cc#L1139)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is used when I construct the UDP message.
</blockquote></details>

per f2f  don't need this.
___
*[examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc, line 8 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lN_Jd8D8oBB683iJa:-M1m0Ew8A6XRe5QOEQkc:b-2yks9w) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc#L8)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think I need the body index to construct the UDP receiver. I do not use it within the UDP message, but I kept it there because drake::math::ExternallyAppliedSpatialForce needs a body index when I convert the UDP message to external spatial force.
</blockquote></details>

per f2f, don't need this.
___
*[examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc, line 148 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lNdai4WgSgsNDb7jq:-M1m0Q131wwsOghPfACB:b-m6dslt) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc#L148)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is used when constructing ExternallyAppliedSpatialForce.
</blockquote></details>

per f2f, don't need it.


<!-- Sent from Reviewable.io -->

2020-03-06 22:51 UTC, hongkai-dai reviewed
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/9)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @hongkai-dai and @rcory)

___
*[examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc, line 148 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lNdai4WgSgsNDb7jq:-M1m1zGr9LX4HKR_vQvK:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc#L148)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

per f2f, don't need it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-06 22:51 UTC, hongkai-dai reviewed
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/9)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @rcory)

___
*[examples/planar_gripper/finger_brick_control.cc, line 1139 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljBka9NLG85U35Rv0:-M1m2-uI2tEtZkCxVClG:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/finger_brick_control.cc#L1139)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

per f2f  don't need this.
</blockquote></details>

Done.
___
*[examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc, line 8 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1lN_Jd8D8oBB683iJa:-M1m20q_3Dqxw3HDbTVz:b-896fix) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/run_planar_gripper_qp_udp_controller.cc#L8)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

per f2f, don't need this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-06 23:48 UTC, hongkai-dai reviewed
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/9)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @rcory)

___
*[examples/planar_gripper/finger_brick_control.cc, line 1139 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljBka9NLG85U35Rv0:-M1mEhP1C40Jv_X0PhUe:b-mwjavx) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/finger_brick_control.cc#L1139)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We do need this one. This brick index is passed into the UDP receiver, and the receiver converts the UDP message to ExternallyAppliedSpatialForce, which uses the body index.


<!-- Sent from Reviewable.io -->

2020-03-07 03:48 UTC, rcory requested changes
> Reviewed 2 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/9)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai and @rcory)

___
*[examples/planar_gripper/finger_brick_control.cc, line 1139 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljBka9NLG85U35Rv0:-M1n5T-IBd3yJuj7lMuL:b-pq2887) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/finger_brick_control.cc#L1139)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We do need this one. This brick index is passed into the UDP receiver, and the receiver converts the UDP message to ExternallyAppliedSpatialForce, which uses the body index.
</blockquote></details>

`GetBrickBodyIndex` in `finger_brick.cc` is going to go away soon. Could you instead call `planar_gripper.get_brick_index()`, like the LCM version?


<!-- Sent from Reviewable.io -->

2020-03-07 15:41 UTC, hongkai-dai reviewed
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/9)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @rcory)

___
*[examples/planar_gripper/finger_brick_control.cc, line 1139 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljBka9NLG85U35Rv0:-M1pdnTD199dqB2IzJPA:b-5lg3rd) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/finger_brick_control.cc#L1139)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

`GetBrickBodyIndex` in `finger_brick.cc` is going to go away soon. Could you instead call `planar_gripper.get_brick_index()`, like the LCM version?
</blockquote></details>

`planar_gripper.get_brick_index()` returns a `ModelInstanceIndex` instead of a `multibody::BodyIndex`. I think we need `BodyIndex` here? The LCM version `ConnectLCMQPController` also uses `GetBrickBodyIndex` to get the brick body index.


<!-- Sent from Reviewable.io -->

2020-03-10 15:05 UTC, rcory approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/rcory/drake/9#-:-M23yfNk-z-OKI-e3_NU:bnfp4nl)* status: 2 of 8 files reviewed, all discussions resolved (waiting on @rcory)

___
*[examples/planar_gripper/finger_brick_control.cc, line 1139 at r1](https://reviewable.io/reviews/rcory/drake/9#-M1ljBka9NLG85U35Rv0:-M23yMXW5VGu4uFhJNFF:b-7zbxcb) ([raw file](https://github.com/rcory/drake/blob/721fac230a62d7fab86a78776827f8cb14238783/examples/planar_gripper/finger_brick_control.cc#L1139)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`planar_gripper.get_brick_index()` returns a `ModelInstanceIndex` instead of a `multibody::BodyIndex`. I think we need `BodyIndex` here? The LCM version `ConnectLCMQPController` also uses `GetBrickBodyIndex` to get the brick body index.
</blockquote></details>

You're right. That's bad nomenclature. I'll make a note to fix this in my refactor branch.


<!-- Sent from Reviewable.io -->

2020-03-10 15:09 UTC, rcory approved these changes
> Reviewed 5 of 8 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/rcory/drake/9)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-03-10 15:10 UTC, merged